version: '3.8'

services:
  mariadb_11:
    image: mariadb:11.4
    container_name: mariadb_11_container
    environment:
      MYSQL_ROOT_PASSWORD: Qwer4321
      LANG: C.UTF-8
      TZ: Europe/Helsinki
    ports:
      - 23306:3306
    volumes:
      - /e/mariadb_11/data:/var/lib/mysql
      - /e/mariadb_11/run:/var/run/mysqld
      - /e/mariadb_11/init_scripts/:/docker-entrypoint-initdb.d/
      - /e/mariadb_11/custom:/opt/custom
      - ./my_utf8mb4.cnf:/etc/mysql/conf.d/my_utf8mb4.cnf
