services:
   mysql_multi_9_5:
     image: mysql:9.5
     container_name: mysql_multi_9_5
     volumes:
       - ./mysql_multi_9_5/data:/var/lib/mysql
       - ./mysql_multi_9_5/run:/var/run/mysqld
       - ./mysql_multi_9_5/init_scripts/:/docker-entrypoint-initdb.d/
     restart: no
     environment:
       MYSQL_ROOT_USER: root
       MYSQL_ROOT_PASSWORD: Qwer4321
       MYSQL_PS1: "mysql_multi_9_5> "
     ports:
       - 43306:3306

   mysql_multi_8_4:
     image: mysql:8.4
     container_name: mysql_multi_8_4
     volumes:
       - ./mysql_multi_8_4/data:/var/lib/mysql
       - ./mysql_multi_8_4/run:/var/run/mysqld
       - ./mysql_multi_8_4/init_scripts/:/docker-entrypoint-initdb.d/
     restart: no
     environment:
       MYSQL_ROOT_USER: root
       MYSQL_ROOT_PASSWORD: Qwer4321
       MYSQL_PS1: "mysql_multi_8_4> "
     ports:
       - 33306:3306

   mysql_multi_8_0:
     image: mysql:8.0
     container_name: mysql_multi_8_0
     volumes:
       - ./mysql_multi_8_0/data:/var/lib/mysql
       - ./mysql_multi_8_0/run:/var/run/mysqld
       - ./mysql_multi_8_0/init_scripts/:/docker-entrypoint-initdb.d/
     restart: no
     environment:
       MYSQL_ROOT_USER: root
       MYSQL_ROOT_PASSWORD: Qwer4321
       MYSQL_PS1: "mysql_multi_8_0> "
     ports:
       - 23306:3306

   mysql_multi_5_7:
     image: mysql:5.7
     container_name: mysql_multi_5_7
     volumes:
       - ./mysql_multi_5_7/data:/var/lib/mysql
       - ./mysql_multi_5_7/run:/var/run/mysqld
       - ./mysql_multi_5_7/init_scripts/:/docker-entrypoint-initdb.d/
     restart: no
     environment:
       MYSQL_ROOT_USER: root
       MYSQL_ROOT_PASSWORD: Qwer4321
       MYSQL_PS1: "mysql_multi_5_7> "
     ports:
       - 53306:3306
