services:
  mariadb_lts:
    image: mariadb:lts
    container_name: mariadb_lts_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Qwer4321
      MYSQL_PS1: "mariadb_lts> "
      LANG: C.UTF-8
    ports:
      - "${DB_PORT:-23306}:3306"
    volumes:
      - /e/mariadb_lts/data:/var/lib/mysql
      - /e/mariadb_lts/run:/var/run/mysqld
      - /e/mariadb_lts/init_scripts/:/docker-entrypoint-initdb.d/
      - /e/mariadb_lts/custom:/opt/custom
      - ./my_utf8mb4.cnf:/etc/mysql/conf.d/my_utf8mb4.cnf
